### CAPSTONE 2 PROJECT
- Vito Muhammad N

** VMN Tourism Consulting**

About Us:  VMN Tourism Consultant is a model startup that was founded in May 2010 and focuses on tourism asset management research in Thailand.<br>

### Project Airbnb host list analysis by Neighbourhood <br>
Project Goals: To know where is the place to make new investment AirBnb at Bangkok.<br>

 ### 1. Businenss Understanding

**Background**<br>

AirBnb's are basically a hotel, but you stay at someone else’s house instead. AirBnB has been everywhere around the world. This analysis is to identify the current state of its value in Bangkok and to identify potential interesting insights. AirBnb in Bangkok has become to the most popular stay in Thailand. There are several type of room in Airbnb and they are have price for each type. The people stay in airbnb sometime is not just a day, it can take for a long stay. The customer gives the reviews to their Airbnb host to make a suggestion to host to make it better in a way. So AirBnb at Bangkok is intresting for make new investment to get profit from Bangkok tourism.<br>

Overall, the main objective for this project is to further understand the insights regarding the AirBnB landscape in Bangkok that have opportunity based on the overview host listings and insights. This project will work with basic analysis methods using Python, and our main success criteria is the ability to find the place of AirBnB listings for new investment.<br>

**Problem Formulation:**<br>

1. Where is the best place investment for new AirBnb host list? <br>
2. What kind of investment that is having highest opportunity for new AirBnb host? <br>
3. What kind of AirBnb’s titles host that appears most often?<br>

 ### 2. Data Understanding<br>

This dataset have 16 columns that give an information about traffic, employee / hoster, and area Airbnb in Bangkok Thailand.
There are the columns and the meanings of each columns: <br>
1. id =  Airbnb's unique identifier for the listing. <br>
2. name = Name of the listing.<br>
3. host_id = Airbnb's unique identifier for the host/user. <br>
4. host_name = Name of the host. Usually, just the first name(s).<br>
5. neighborhood = The neighborhood is geocoded using the latitude and
longitude against neighborhoods as defined by open or public
digital shapefiles.<br>
6. latitude = Uses the World Geodetic System (WGS84) projection for
latitude and longitude.<br>
7. Longitude = Uses the World Geodetic System (WGS84) projection for
latitude and longitude.<br>
8. room_type = [Entire home/apt |Private room| Shared room| Hotel] <br>

Entire Room : Entire places are best if you're seeking a home away from
home. With an entire place, you'll have the whole space to
yourself. This usually includes a bedroom, a bathroom, a
kitchen, and a separate, dedicated entrance. Hosts should
note in the description if they'll be on the property or not (ex:
"Host occupies the first floor of the home") and provide further
details on the listing.<br>

Private Room: Private rooms are great for when you prefer a little privacy,
and still value a local connection. When you book a private
room, you'll have your private room for sleeping and may
share some spaces with others. You might need to walk
through indoor spaces that another host or guest may occupy
to get to your room.<br>

Shared Room: Shared rooms are for when you don't mind sharing a space
with others. When you book a shared room, you'll be sleeping
in a space that is shared with others and share the entire
space with other people. Shared rooms are popular among
flexible travelers looking for new friends and budget-friendly stays<br>

9. price = Daily price in local currency. Note, the $ sign may be used
despite the locale.<br>
10. minimum_nights = The minimum number of night stays for the listing (calendar
rules may differ).<br>
11. number_of_reviews = The number of reviews the listing has.<br>
12. last_review = The date of the last/newest review.<br>
13. review_per_month = The month of the last review on month <br>
14. calculated_host_listings_count = The number of listings the host has in the current scrape in
the city/region geography.<br>
15. availability_365 = avaliability_x. The calendar determines the availability of the
listing x days in the future. Note a listing may be available
because it has been booked by a guest or blocked by the
host.<br>
16. number_of_reviews_itm = The number of reviews the listing has (in the last 12 months).<br>

**Analysis**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option("display.max_columns", None)

In [2]:
# Import data for AirBnB Bangkok listing
df = pd.read_csv('../data/airbnb_listings_bangkok.csv')
df.head()

,Unnamed: 0,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
0,0,27934,Nice room with superb city view,120437,Nuttee,Ratchathewi,13.75983,100.54134,Entire home/apt,1905,3,65,2020-01-06,0.50,2,353,0
1,1,27979,"Easy going landlord,easy place",120541,Emy,Bang Na,13.66818,100.61674,Private room,1316,1,0,NaN,NaN,2,358,0
2,2,28745,modern-style apartment in Bangkok,123784,Familyroom,Bang Kapi,13.75232,100.62402,Private room,800,60,0,NaN,NaN,1,365,0
3,3,35780,Spacious one bedroom at The Kris Condo Bldg. 3,153730,Sirilak,Din Daeng,13.78823,100.57256,Private room,1286,7,2,2022-04-01,0.03,1,323,1
4,4,941865,Suite Room 3 at MetroPoint,610315,Kasem,Bang Kapi,13.76872,100.63338,Private room,1905,1,0,NaN,NaN,3,365,0

In [3]:
# Identify overview data information of the latest listing file
df.describe()

,Unnamed: 0,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,15854.000000,1.585400e+04,1.585400e+04,15854.000000,15854.000000,1.585400e+04,15854.000000,15854.000000,10064.000000,15854.000000,15854.000000,15854.000000
mean,7926.500000,1.579397e+17,1.541058e+08,13.745144,100.559903,3.217704e+03,15.292355,16.654157,0.813145,13.889618,244.378643,3.481519
std,4576.799919,2.946015e+17,1.318726e+08,0.043040,0.050911,2.497212e+04,50.815020,40.613331,1.090196,30.269848,125.843224,8.916937
min,0.000000,2.793400e+04,5.892000e+04,13.527300,100.329550,0.000000e+00,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,3963.250000,2.104509e+07,3.974431e+07,13.720090,100.529690,9.000000e+02,1.000000,0.000000,0.120000,1.000000,138.000000,0.000000
50%,7926.500000,3.503734e+07,1.224556e+08,13.738490,100.561415,1.429000e+03,1.000000,2.000000,0.435000,4.000000,309.000000,0.000000
75%,11889.750000,5.256154e+07,2.390547e+08,13.759497,100.585150,2.429000e+03,7.000000,13.000000,1.060000,13.000000,360.000000,3.000000
max,15853.000000,7.908162e+17,4.926659e+08,13.953540,100.923440,1.100000e+06,1125.000000,1224.000000,19.130000,228.000000,365.000000,325.000000

In [4]:
# Identify the total size of the data to be analysed
df.shape

(15854, 17)

In [5]:
print(f'Number of lines from dataset is ("Row, columns") {df.shape}')
df.info()

Number of lines from dataset is ("Row, columns") (15854, 17)
<class 'pandas.DataFrame'>
RangeIndex: 15854 entries, 0 to 15853
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      15854 non-null  int64
 1   id                              15854 non-null  int64
 2   name                            15846 non-null  str
 3   host_id                         15854 non-null  int64
 4   host_name                       15853 non-null  str
 5   neighbourhood                   15854 non-null  str
 6   latitude                        15854 non-null  float64
 7   longitude                       15854 non-null  float64
 8   room_type                       15854 non-null  str
 9   price                           15854 non-null  int64
 10  minimum_nights                  15854 non-null  int64
 11  number_of_reviews               15854 non-null  int64
 12  last_review                     10064 non-null  str
 13  reviews_per_month               10064 non-null  float64
 14  calculated_host_listings_count  15854 non-null  int64
 15  availability_365                15854 non-null  int64
 16  number_of_reviews_ltm           15854 non-null  int64
dtypes: float64(3), int64(9), str(5)
memory usage: 2.1 MB

In [6]:

df['last_review'] = df['last_review'].astype('datetime64[ns]')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15854 entries, 0 to 15853
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      15854 non-null  int64
 1   id                              15854 non-null  int64
 2   name                            15846 non-null  str
 3   host_id                         15854 non-null  int64
 4   host_name                       15853 non-null  str
 5   neighbourhood                   15854 non-null  str
 6   latitude                        15854 non-null  float64
 7   longitude                       15854 non-null  float64
 8   room_type                       15854 non-null  str
 9   price                           15854 non-null  int64
 10  minimum_nights                  15854 non-null  int64
 11  number_of_reviews               15854 non-null  int64
 12  last_review                     10064 non-null  datetime64[ns]
 13  reviews_per_month               10064 non-null  float64
 14  calculated_host_listings_count  15854 non-null  int64
 15  availability_365                15854 non-null  int64
 16  number_of_reviews_ltm           15854 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(9), str(4)
memory usage: 2.1 MB

In [7]:
df.to_excel('AirBnb_new_clean.xlsx',index=False) #index false

ModuleNotFoundError: No module named 'openpyxl'

Save to new file for easier cleansing

In [ ]:
df1 = pd.read_excel('AirBnb_new_clean.xlsx')

In [ ]:
#Drop Columns irrelevant
df1.drop(['host_name','Unnamed: 0'], axis=1, inplace=True)

In [ ]:
df1['year'] = df1['last_review'].dt.year
df1['month'] = df1['last_review'].dt.month
df1.info()

In [ ]:
df1['month'] = df1['last_review'].dt.month_name()

In [ ]:
#Check missing value based on heatmap
plt.figure(figsize=(10,5))
sns.heatmap(df1.isnull(),cbar=False)
plt.title('Heatmap Missing Value')
plt.savefig('missing value.jpeg')
plt.show()

In [ ]:
df1.isnull().sum()

In [ ]:
last_review_miss = (df1['last_review'].isnull().sum()/len(df1))*100
print(f'Total numbers missing value of last_review column is {last_review_miss}% from the all lines data')
reviews_per_month_miss = (df1['reviews_per_month'].isnull().sum()/len(df1))*100
print(f'Total numbers missing value of review per month column is {reviews_per_month_miss}% from the all lines data')

On general, we can know:<br>
1. Dataset have 15854 rows and 17 columns before remove irrelevant columns, but after we delete the columns and add seperate data from a column exist, we have 15 columns  .<br>
2. Column 'id' and 'host_name' and 'unnamed: 0' can be drop because there are not irrelevant and they just show the number of airbnb's listing unique.<br>
3. On several columns as last_review and review_per_month have 5790 missing value, or the data is empty or NaN. It takes 36% of the data<br>
4. Column 'last_review' has to change the datatype to Datetime<br>
5. Dataset doesn't have duplicate.<br>
6. Column 'Number of Review' have the large range. This column only show the frecuency of customer review on hosting, so the columns is not to do nothing to change.<br>

**Handle Missing Value**:
We were going to handle those missing value with fill the missing value, because the missing value is  categoric so it is important and cant be delete.<br>
1. Column name replacing blank enriess in 'name' with 'no description'
2. Column Review per Month replacing blank entries in 'reviews_per_month' column with 0s. <br>
3. Column last review replacing blank entries in 'last_review' column with 0s.<br>
4. Column year replacing blank entries in 'year' column with 0s.<br>
5. Columns month replacing blank entries in 'month' column with 0s.<br>

In [ ]:
#fill missing value
df1.name = df1.name.fillna('no description')
df1.fillna({'reviews_per_month':0}, inplace=True)
df1.fillna({'last_review':0}, inplace=True)

df1.fillna({'year':0}, inplace=True)
df1.fillna({'month':0}, inplace=True)

***Check and Handling Outliers***

In [ ]:
pd.set_option('display.max_colwidth', None)
# data uni di tiap kolom
listItem = []
for col in df1.columns :
    listItem.append( [col, df1[col].nunique(), df1[col].unique()])

tabel1Desc = pd.DataFrame(columns=['Column Name', 'Number of Unique', 'Unique Sample'],
                     data=listItem)
tabel1Desc

In [ ]:
numericals = ['price','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','number_of_reviews_ltm']
categoricals = ['name','neighbourhood','room_type','last_review']

In [ ]:
features = numericals
plt.figure(figsize=(20,10))
for i in range(0, len(features)):
    plt.subplot(1, len(features), i+1)
    sns.boxplot(y=df1[features[i]], color = 'green', orient = 'v')
    plt.tight_layout()
plt.title('Distribution from numericals data by Boxplot')
plt.savefig('Distribution before cleansing.jpeg')

In [ ]:
features = numericals
plt.figure(figsize=(20,10))
for i in range(0, len(features)):
    plt.subplot(3,3, i+1)
    sns.histplot(df1[features[i]],kde=True)
    plt.tight_layout()
plt.title('Distribution from numericals data by Boxplot')

There are not have any normal distrubution, so we can judge the outlier by percentile. This method is reference from the article [[1]](https://www.analyticsvidhya.com/blog/2021/05/feature-engineering-how-to-detect-and-remove-outliers-with-python-code/#:~:text=Use%20a%20percentile%2Dbased%20approach,percentile%20are%20considered%20an%20outlier).

In [ ]:
# observing descriptive statistics of all variables
df1.describe(percentiles = [0.25, 0.5, 0.75, 0.95, 0.97])

In [ ]:
pd.DataFrame(df1['minimum_nights'].sort_values(ascending=False))

In [ ]:
lower_bound = df1["price"].quantile(0.01)
upper_bound  = df1["price"].quantile(0.99)

df1 = df1[(df1["price"] < upper_bound) & (df1["price"] > lower_bound)]

In [ ]:
### membuang kolom umur diatas 100 tahun
### memfilter hanya umur dibawah 100 tahun

df1 = df1[df.minimum_nights <= 30]
df1

In [ ]:
numericals2 = ['price','minimum_nights','number_of_reviews','reviews_per_month','calculated_host_listings_count','availability_365','number_of_reviews_ltm']
categoricals2 = ['name','neighbourhood','room_type','last_review']

After filtering outlier with percentile

In [ ]:
features = numericals2
plt.figure(figsize=(20,10))
for i in range(0, len(features)):
    plt.subplot(1, len(features), i+1)
    ax = sns.boxplot(y=df1[features[i]], color = 'green', orient = 'v')
    plt.tight_layout()
ax.set_title('Distribution of numericals by Boxplot')
plt.savefig('Distribution clean.jpeg')

In [ ]:
print(f'Total data df1 is {len(df)}')
print(f'Total data df2 is {len(df1)}')
print(f'Total {(len(df)-len(df1))}')

In [ ]:
df1[['price','minimum_nights','number_of_reviews','calculated_host_listings_count','availability_365','number_of_reviews_ltm']].describe()

**---------- Use Clean Data----------**

***Check Correlation***

In [ ]:
correlation = df1.corr(method='spearman', numeric_only=True)
correlation

In [ ]:
plt.figure(figsize=(10,5))

mask = np.triu(np.ones_like(correlation))
sns.heatmap(correlation, annot=True,linewidths=1,fmt='.2f',cmap='coolwarm',vmin=-1, vmax=1, mask=mask, annot_kws={'size':10})
plt.show()

In [ ]:
median_occ = df1['availability_365'].median()
all_sold = median_occ - 365

print(f'Total days that AirBnb room all sold out at the same day is {abs(all_sold)} days')

1. top 10 areas in Bangkok with the most listing count? How many listings are there?

In [ ]:
neighbor_cleaned_price_data = df1.groupby('neighbourhood')['price'].sum().reset_index().sort_values('price',ascending=False)
neighbor_cleaned_count_data = df1['neighbourhood'].value_counts().reset_index().rename(columns=({'neighbourhood':'Area','count':'total'}))

In [ ]:
neighbor_cleaned_count_data['rank'] = neighbor_cleaned_count_data['total'].rank(ascending=False)

In [ ]:
neighbor_cleaned_count_data.head()

In [ ]:
neighbor_cleaned_count_data.to_excel('neighbor_cleaned_count_data.xlsx')

In [ ]:
plt.figure(figsize = (15,8))
clrs = ['grey' if (x < max(neighbor_cleaned_count_data.total)) else 'red' for x in neighbor_cleaned_count_data.total ]
ax = sns.barplot(data=neighbor_cleaned_count_data.head(10),y='Area',x='total',palette=
                 clrs)
for p in ax.patches:
    ax.annotate("%.0f listings" % p.get_width(), xy=(p.get_width(), p.get_y()+p.get_height()/2),
            xytext=(-70, 0), textcoords='offset points', ha="left", va="center", color = 'white')
plt.title('Top 10 count of Host List by Neighbourhood')
plt.savefig('Top 10 count of Host List by Neighbourhood.jpeg')

Interpretasi: AirBnb at Area Vadhana, Khlong Toei, ratchattadewi, huai kwhank, and bang rak are become the most list AirBnb to stay in Bangkok based on count on list host.

2.Where is the top 15 total value of AirBnB listings in Bangkok by Area?

In [ ]:
neighbor_cleaned_price_data.head(10)

In [ ]:
# Select top 10 neighborhood data to plot
top10_neighborhood_price = neighbor_cleaned_price_data.nlargest(15,columns='price').sort_values('neighbourhood',ascending=False)
top10_neighborhood_price = top10_neighborhood_price.sort_values('price',ascending=False)
clrs = ['grey' if (x < max(top10_neighborhood_price.price)) else 'red' for x in top10_neighborhood_price.price ]

# Set figure plot size and plot data
plt.figure(figsize = (15,8))
# Plot to show the top 15 largest neighborhood by total listing. 
# Showing top 10 instead as more variation
ax = sns.barplot(data = top10_neighborhood_price.head(10),x="price",y='neighbourhood',palette=clrs)

# Setup styling and listing values
for p in ax.patches: 
    ax.annotate("THB  %.0f" % p.get_width(), xy=(p.get_width(), p.get_y()+p.get_height()/2),
            xytext=(-80, 0), textcoords='offset points', ha="left", va="center", color = 'white')
# for c in ax.containers:
#     ax.bar_label(c, labels=[f'THB {x:,.0f}' for x in c.datavalues])
plt.rcParams["axes.labelsize"] = 12
plt.grid(color = 'grey', linestyle = '--', linewidth = 0.3)
plt.title("Top 10 Total listing value by neighbourhood (bath)")
plt.ylabel("Bangkok neighbourhood",labelpad=15)
plt.ticklabel_format(style='plain', axis='x')
plt.savefig('top 10 total value of AirBnB listings in Bangkok by Area.jpeg')

Interpretasi: AirBnb at Area Vadhana, Khlong Toei, ratchattadewi, huai kwhank, and bang rak are become the highest valauation in Bangkok based on total price per day. <br>

In [ ]:
figure, axes = plt.subplots(1,2,figsize=(30,10))
figure.suptitle('Comparison between top 10 count of host list by count and valuation neighbourhood',size=14, fontweight='bold')
clrs = ['grey' if (x < max(neighbor_cleaned_count_data.total)) else 'red' for x in neighbor_cleaned_count_data.total ]
sns.barplot(data=neighbor_cleaned_count_data.head(10),y='Area',x='total',palette=
                 clrs, ax=axes[0])
for p in axes[0].patches:
    axes[0].annotate("%.0f listings" % p.get_width(), xy=(p.get_width(), p.get_y()+p.get_height()/2),
            xytext=(-70, 0), textcoords='offset points', ha="left", va="center", color = 'white')
axes[0].set_title('Top 10 Count of Host List by Count Neighbourhood')
sns.barplot(data = top10_neighborhood_price.head(10),x="price",y='neighbourhood',palette=clrs,ax=axes[1])
for p in axes[1].patches: 
    axes[1].annotate("THB  %.0f" % p.get_width(), xy=(p.get_width(), p.get_y()+p.get_height()/2),
            xytext=(-80, 0), textcoords='offset points', ha="left", va="center", color = 'white')
plt.rcParams["axes.labelsize"] = 12
plt.grid(color = 'grey', linestyle = '--', linewidth = 0.3)
axes[1].set_title('Top 10 Count of Host List by Valuation per Neighbourhood')
plt.savefig('camparison.jpeg',dpi=1000)

3. What is the most common room type available and common price of the room type?<br>

**Room type vs Minimum Nights**

In [ ]:
# using countplot to visualize the number of Airbnbs by room type
ax = sns.countplot(x='room_type', data=df1, order=df1['room_type'].value_counts().index)
abs_values = df1['room_type'].value_counts(ascending=False)
rel_values = df1['room_type'].value_counts(ascending=False, normalize=True).values * 100
lbls = [f'{p[0]} ({p[1]:.0f}%)' for p in zip(abs_values, rel_values)]
ax.bar_label(container=ax.containers[0], labels=lbls) #puts the labels on the bars
ax.set_title('Number of Listings by Room Type')
plt.xticks(rotation=0)
plt.savefig('Number of host listing by room type.jpeg')
plt.show()

Interpretasi: The Most Airbnb's type room in Bangkok is Entire home/apt. But the less room in Bangkok is Shared room.

In [ ]:
df2_room_minimum_stay = df1.groupby('room_type').agg({'minimum_nights':np.median}).sort_values('minimum_nights',ascending=False).reset_index()
df2_room_minimum_stay

Interpretasi: From room type minimum nights, we can know that minimum nights to stay is 1 night, except entire home/apt is 2 nights.

**Room type vs Price**

In [ ]:
df2_room_price = df1.groupby('room_type').agg({'price':np.median}).sort_values('price',ascending=False).reset_index()
df2_room_price

Interpretasi: The most expensive of AirBnb room type is Hotel room, but the cheapest is Shared room.

**Statistic Inferensia**

In [ ]:
from scipy.stats import kruskal

H0: There is no significant difference between price and room type on Airbnb.<br>
H1: There is a significant difference between price and room type on Airbnb.<br>

In [ ]:
# separate data into independent variable (harga) and dependent variable (tipe kamar)
tipe_kamar = df1["room_type"]
harga = df1["price"]

# perform Kruskal-Wallis test
result = kruskal(*[harga[tipe_kamar == tipe] for tipe in tipe_kamar.unique()])

# print results
print("Kruskal-Wallis H-test")
print("H-statistic:", result.statistic)
print("p-value:", result.pvalue)

Interpretasi: We get p-value < 0.05, the meaning is there is a significant difference between price and room type on Airbnb. So more expensive price will get higher classification of room type

Room Type Hotel Room is the most expensive type room based on median

4. What is the most name listing in Airbnb bangkok? <br>

In [ ]:
# Analyzing the words used by hosts when naming their listings
# getting list of all names
names = df1['name'].tolist()
name_words = []
for name in names:
    name = str(name).split()
    for word in name:
        name_words.append(word.lower())

In [ ]:
import nltk # natural language toolkit
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

filtered_words = [word for word in name_words if word not in stopwords.words('english')]
print(filtered_words[:25])

In [ ]:
from collections import Counter # to count words in our list

# plotting top 25 words used by the host in naming their home
words_count = Counter(filtered_words).most_common()
words_count = words_count[:25]

In [ ]:
# converting the data into a dataframe so we can plot it using Seaborn
words_df = pd.DataFrame(words_count)
words_df.head(10)

In [ ]:
words_df.rename(columns={0:"Words", 1:"Count"}, inplace=True)

In [ ]:
plt.figure(figsize=(10,5))
fig, ax = plt.subplots()
fig.suptitle('Top 25 Words Used in Bangkok Airbnb Names')
sns.barplot(x='Words', y='Count', data=words_df, ax=ax)
plt.xticks(rotation=80)
plt.savefig('Top 25 Words Used In Bangkok AirBnb Names.png',dpi=800,bbox_inches='tight')
plt.show()

Interpretasi: Usually host AirBnb in Bangkok use ‘bts, room, near, Bangkok, Sukhumvit, bedroom’ in their title names. From the word we can know where is the place of host AirBnb and what they want to show to customer.

6. What type room is most often reviewd?

In [ ]:
df_area = df1.groupby('room_type').agg({'number_of_reviews':sum}).sort_values('number_of_reviews',ascending=False).reset_index()
df_area

In [ ]:
df_area['percentage'] = df_area['number_of_reviews']/df_area['number_of_reviews'].sum()

In [ ]:
df_area

In [ ]:
ax = sns.barplot(data=df_area,x='room_type',y='number_of_reviews')
abs_values = df_area['number_of_reviews']
rel_values = df_area['percentage']* 100
lbls = [f'{p[0]} ({p[1]:.0f}%)' for p in zip(abs_values, rel_values)]
ax.bar_label(container=ax.containers[0], labels=lbls) #puts the labels on the bars
plt.title('Sum of count review by room_type')
plt.savefig('Total count review by room type.jpeg',bbox_inches='tight')

Interpretasi: If we asumption that most of the customer fill the review, entire home/apt is will the sexiest AirBnb room and the most sold type room based on review count.

In [ ]:
plt.figure(figsize = (15,8))
clrs = ['grey' if (x < max(neighbor_cleaned_count_data.total)) else 'red' for x in neighbor_cleaned_count_data.total ]
ax = sns.barplot(data=neighbor_cleaned_count_data.head(10),y='Area',x='total',palette=
                 clrs)
for p in ax.patches:
    ax.annotate("%.0f listings" % p.get_width(), xy=(p.get_width(), p.get_y()+p.get_height()/2),
            xytext=(-70, 0), textcoords='offset points', ha="left", va="center", color = 'white')

In [ ]:
area = df1.groupby(['neighbourhood','room_type']).size().reset_index().rename(columns={0:'total'}).sort_values('total', ascending=False)
area

In [ ]:
area_entire = area[area['room_type']=='Entire home/apt'].sort_values('total',ascending=False)
area_entire.head()

top 10 Count entire home by neigghbourhood

In [ ]:
plt.figure(figsize=(16,8))
clrs = ['grey' if (x > min(area_entire.head(10).total)) else 'red' for x in area_entire.head(10).total ]
ax = sns.barplot(data= area_entire.head(10),y='neighbourhood',x='total',palette=clrs)
for p in ax.patches:
    ax.annotate("%.0f listings" % p.get_width(), xy=(p.get_width(), p.get_y()+p.get_height()/2),
            xytext=(-60, 0), textcoords='offset points', ha="left", va="center", color = 'white')
plt.title('Top 10 Entire home/apt room Airbnb List by Neighbourhood')
plt.savefig('top 10 Count entire home by neigghbourhood.jpeg')

Interpretasi: From chart above, we can see Parthum Wan is the less have home/apt room in top 10 neighbourhood by jome/apt room type.

top 5 Count room type by neigghbourhood

In [ ]:
ax = sns.barplot(data= area_entire.head(5),x='neighbourhood',y='total')
for i in ax.containers:
    ax.bar_label(i,)
plt.title('Top 5 Entire home/apt Airbnb List by Neighbourhood')
plt.savefig('Count entire home by neigghbourhood.jpeg',bbox_inches='tight')

Interpretasi: From the top 5 entire home/ apt list by neighbourhood in Bangkok, Khlong Toei has the most types of apartment rooms.

In [ ]:
area_budget = area[area['room_type']=='Shared room'].sort_values('total',ascending=False)
area_budget.head()

In [ ]:
ax = sns.barplot(data= area_budget.head(5),x='neighbourhood',y='total')
for i in ax.containers:
    ax.bar_label(i,)
plt.title('Top 5 Budget Airbnb List by Neighbourhood')
plt.savefig('Count budget by neigghbourhood.jpeg',bbox_inches='tight')

Interpretasi: From the top 5 Budget room list by neighbourhood in Bangkok, Phra Nakhon has the most types of apartment rooms.

In [ ]:
area_private = area[area['room_type']=='Private room'].sort_values('total',ascending=False)
area_private.head()

In [ ]:
ax = sns.barplot(data= area_private.head(5),x='neighbourhood',y='total')
for i in ax.containers:
    ax.bar_label(i,)
plt.title('Top 5 Private room Airbnb List by Neighbourhood')
plt.savefig('Count Private room by neigghbourhood.jpeg',bbox_inches='tight')

Interpretasi: From the top 5 Private room list by neighbourhood in Bangkok, Vadhana has the most types of apartment rooms.

In [ ]:
area_hotel = area[area['room_type']=='Hotel room'].sort_values('total',ascending=False)
area_hotel.head()

In [ ]:
ax = sns.barplot(data= area_hotel.head(5),x='neighbourhood',y='total')
for i in ax.containers:
    ax.bar_label(i,)
plt.title('Top 5 Hotel room Airbnb List by Neighbourhood')
plt.savefig('Top 5 Hotel room Airbnb List by Neighbourhood.jpeg',bbox_inches='tight')

Interpretasi: From the top 5 hotel room list by neighbourhood in Bangkok, vadhana Toei has the most types of apartment rooms.

**Conclusion:**<br>
1. From a year the availability of the listing x days in the future, every AirBnb host in Bangkok ready for their room for 308 days in year based on median. The rest of day a listing may be not available because it has been booked by a guest or blocked by the host. <br>
2. AirBnb at Area Vadhana, Khlong Toei, ratchattadewi, huai kwhank, and bang rak are become the most list AirBnb to stay in Bangkok based on  count on list host and valuation per area. <br>
3. The Most Airbnb's type room in Bangkok is Entire home/apt.<br>
4. AirBnb common rules of minimum stayed is 2 nights for room type entire home / apt, and the other room type is 1 night.<br>
5. There is a significant difference between price and room type on Airbnb<br>
5. The most expensive room type is hotel room.<br>
6. AirBnb Popular name by host listing in bangkok are bts,room, near, bangkok, sukhumvit, cozy, and mrt.<br>
7. If we asumption that most of the customer fill the review, entire home/apt will is the sexiest AirBnb room and the most sold type room based on review count. <br>

***Business Recomendation***

1. - The new applicant that want to join as a host for AirBnb in Bangkok, we suggest you to should have the AirBnb arround sukhumvit road either in vadhana or khlong toei. 
   - It is busy city to shopping hub with huge malls offering luxury fashion and artisanal goods, plus food courts and posh international dining. Vadhana and khlong toei also is in sukhumvit area. Which is the tourist most visit area. Sukhimvit is the best neighborhood overall. The public transportation and the vibes is awsome there.[[1]](https://thenomadvisor.com/where-to-stay-in-bangkok/)<br>
   - Ratchadewi and  huwaikwang are the best option place after vadhana area to built a new AirBnb. 
   - They are near to the central tourist visit. Huwaikwang is very famous with their night market[[4]](https://thailand.tripcanvas.co/bangkok/huai-kwang-night-market/). other than that the Ratchathewi city is a popular destination for medical tourism, with several world-class hospitals located in the area offering affordable medical treatments and procedures[[2]](https://travelodium.com/things-to-do-in-ratchathewi-bangkok-thailand/#:~:text=The%20Victory%20Monument%2C%20one%20of%20Bangkok%E2%80%99s%20most%20famous,including%20Wat%20Mangkon%20Kamalawat%20and%20Wat%20Hua%20Lamphong). <br>
2. - The new AirBnb host should have room more than 50% with the type room is entire home/apt. So, we suggest the highest opportunity investment by roomtype for new AirBnb host should have room more than 50% with the type room is entire home/apt.<br> 
   - if you want to build entire home/apt or hotel room or private room, Khlong toei and vadhana is the great place for your AirBnb's room.<br>
   - If you want to build budget AirBnb, Bang Lamphu[[3]](https://www.thebrokebackpacker.com/where-to-stay-in-bangkok-thailand/) in Phra Nakhon District is the great place. Banglamphu is the heart and soul of Bangkok. Centrally located, this neighbourhood is where you’ll find an excellent mix of historic and beautiful temples and a vibrant and lively party scene.<br>
   - There is a large opportunity to build entire home/apt room at Siam area in Parthum Wan district, Siam at Parthum Wan is the commercial centre of Bangkok and one of the city’s safest neighbourhoods, making it one of the best areas to stay for families[[3]](https://www.thebrokebackpacker.com/where-to-stay-in-bangkok-thailand/). But There are not much entire home/apt in Parthum Wan.<br>
3. - To make it easier for your Airbnb title to be easily found by customers, we suggest you to use word ‘bts, room, near, Bangkok, bedroom, 1(room), 2(room), view, new, city, MRT’ in your title names. But it depends what your asset provide to AirBnb’s Customer.<br>

Reference:

Handling Outliers:<br>
[1]Royal, C. (2021, 05 19). Outlier Detection & Removal | How to Detect & Remove Outliers (Updated 2023). Retrieved from analyticsvidhya: https://www.analyticsvidhya.com/blog/2021/05/feature-engineering-how-to-detect-and-remove-outliers-with-python-code/#:~:text=Use%20a%20percentile%2Dbased%20approach,percentile%20are%20considered%20an%20outlier. <br>

Recommendation:<br>
[1] thenomadvisor. (n.d.). Where to Stay in Bangkok: 10 Best Areas. Retrieved from thenomadvisor: https://thenomadvisor.com/where-to-stay-in-bangkok/ <br>
[2]travelodium. (n.d.). Things to do in Ratchathewi – Bangkok – Thailand. Retrieved from travelodium.com: https://travelodium.com/things-to-do-in-ratchathewi-bangkok-thailand/#:~:text=The%20Victory%20Monument%2C%20one%20of%20Bangkok%E2%80%99s%20most%20famous,including%20Wat%20Mangkon%20Kamalawat%20and%20Wat%20Hua%20Lamphong<br>
[3]Cathryn, C. (2023, 04 28). Where to Stay in Bangkok (COOLEST Areas • 2023). Retrieved from thebrokebackpacker: https://www.thebrokebackpacker.com/where-to-stay-in-bangkok-thailand/<br>
[4]Pillay, D. (n.d.). 5 Reasons to visit Huai Kwang Night Market in Bangkok. Retrieved from thailand.tripcanvas.co: https://thailand.tripcanvas.co/bangkok/huai-kwang-night-market/

In [ ]:
df1.to_excel('AirBnb_Tablue.xlsx')